server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://ee417db.crxkzf89o3fh.eu-west-1.rds.amazonaws.com:3306/GroupE_Assignment
    username: EE417
    password: EE417_2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect